
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://context_user:context_password@postgres:5432/context_server
      - LOG_LEVEL=INFO
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PYTHONPATH=/app
    volumes:
      - ./context_server:/app/context_server
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn context_server.api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=context_user
      - POSTGRES_PASSWORD=context_password
      - POSTGRES_DB=context_server
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U context_user -d context_server"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: context_server_network
